# Generated by Django 3.0.7 on 2020-06-26 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_desc',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
    ]
